### ISSUE TITLE
Extension causes JSON parse error when loading SharePoint page

### ISSUE THREAD

**Issue by jrossstocholm** [bhollis/jsonview#210]
**Describe the bug**
When I have the extension enabled I cannot load our internal SharePoint intranet. When I disable the extension, the page loads fine but after enabling it (repeatedly) the load of the page fails.

I have used the extension for about 6 months, and I have not seen this error before. Maybe it was caused by the December 17th update.

The error is

"There was an error parsing the JSON document. The document may not be well-formed."

**What browser are you using?***
I am using Edge on Windows

**Where did you install JSONView from?**
I have installed it through Microsoft extension Store.

![image](https://github.com/bhollis/jsonview/assets/683942/5fbf42e7-1151-4c81-a77a-f50e6c319838)

**Comment by stanio** [comment]
I was experiencing this intermittently in the past and I've identified the cause was not JSONView alone.  After disabling all but the JSONView extension the problem was not occurring for me.  I've reenabled other extensions one at a time and ultimately identified another extension (don't remember which one) that was causing the problem.  In my case, I've dropped the usage of that other extension.

**Comment by jrossstocholm** [comment]
> I was experiencing this intermittently in the past and I've identified the cause was not JSONView alone. After disabling all but the JSONView extension the problem was not occurring for me. I've reenabled other extensions one at a time and ultimately identified another extension (don't remember which one) that was causing the problem. In my case, I've dropped the usage of that other extension.

Since I am on a company-controlled version of Edge, I do not have full control over the extensions. My current extensions are these

![image](https://github.com/bhollis/jsonview/assets/683942/e6de2e25-869a-450a-9ec8-92cbd96ccff6)

If I re-enable JSONVIEW it breaks - if I disable it, it works fine. I cannot disable the "iswebhook" extension, so I cannot for sure say that it is not a combination of these two. I can say, however, that I noticed the new behaviour around Christmas - so it sort of fits with the new update of the extension.

I will look into having the "iswebhook" extension disabled to trouble-shoot further 😊

**Comment by jrossstocholm** [comment]
I was just told that the "iswebhook" extension (Lakeside Systrack Agent) was installed on our PCs in March 2023, so this extension and JSONview has been living nicely side by side for almost 9 months.

I will continue to investigate if I can disable it to confirm the root cause of SharePoint load issues.

**Comment by bhollis** [comment]
It seems likely that removing the webRequestBlocking permission is the culprit - it works for directly viewing JSON but SharePoint must be doing something weird. Unfortunately if that's the case JSONView will cease to be after the ManifestV3 transition.

**Comment by subbink** [comment]
I can confirm the issue as well when using firefox 120.0.1 on linux.

**Comment by Oneill701** [comment]
Hello,

I have the same error in Edge when I open a SharePoint site. If I deactivate this extension it works again.
I think it's link to the last version of Edge.
I have problem too when I open a public link : https://cdn.ruckzuck.tools/rest/v2/getsoftwares?apikey=45820419983905&shortname=Google%20Chrome
It's now correctly format in Edge with the extension deactivate. So I think Edge directly integrate a JSON formater.

Other link for test : https://[microsoftedge.github.io/Demos/json-dummy-data/256KB-min.json](https://microsoftedge.github.io/Demos/json-dummy-data/256KB-min.json)

**Comment by bhollis** [comment]
I've submitted a new version of JSONView, I don't know when it'll be approved.

**Comment by qmacro** [comment]
> SharePoint must be doing something weird

I would say so - I experience this issue too with Sharepoint sites, and noticed that Sharepoint returns content type application/json for main (web) page requests. Sharing this here just in case it helps.

![Screenshot 2024-02-03 at 15 37 21](https://github.com/bhollis/jsonview/assets/73068/0ec90f25-2666-4f95-af39-3f63688e7ddf)

**Comment by calvinhsia** [comment]
I get the same error: 
 
MSEdge (Version 122.0.2365.80 (Official build) (64-bit)) returns: "There was an error parsing the JSON document. The document may not be well-formed." However, there is no error, as the developer tools shows. 
Works fine in FireFox browser and Postman.  Fiddler shows JSON is fine.
Sometimes works in Edge InPrivate view.
Simple repro in Azure Function that returns raw JSON.

        [Function(nameof(UploadBinary))]
        public async Task<IActionResult> UploadBinary([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", "patch")] HttpRequest req)
        {
            var mynewobj = new
            {
                Name = "foobar",
                City = "redmond"
            };
            return new JsonResult(mynewobj);

**Comment by bhollis** [comment]
Is this still happening on the 3.0.0 version of JSONView?

**Comment by subbink** [comment]
I'll have a look when 3.0.0 is available from the firefox add-ons site.

**Comment by DidierLoiseau** [comment]
I just checked and it seems ok now for me.

**Comment by bhollis** [comment]
Cool, feel free to reopen if this re-occurs.

**Comment by subbink** [comment]
When using version 3.0.1, I still get an error.
```
There was an error parsing the JSON document. The document may not be well-formed.
unexpected character at line 1 column 1
Skip to main content
Home
Currently following the site, click to stop following
```

**Comment by bhollis** [comment]
That's unfortunate. Can you provide me with a Sharepoint site I can access to test with?

**Comment by subbink** [comment]
> That's unfortunate. Can you provide me with a Sharepoint site I can access to test with?

No, sorry. It is the company's sharepoint and I'm only a user.

**Comment by bhollis** [comment]
OK well I'll reopen it but I can't do anything until I can see a site like this.

**Comment by hylkevds** [comment]
You could try this sharepoint site: https://fraunhofer.sharepoint.com/
I'm on Firefox 128.0 and also have the same issue.

**Comment by hylkevds** [comment]
As an intermediate solution, would it be possible to add a quickly accessible toggle to turn jsonview on and off? Right now it takes several clicks to turn it off, and a few more clicks to turn it back on.

**Comment by dvogel** [comment]
I too have an issue with JSONView conflicting with SharePoint sites. Unfortunately I cannot provide access to any of these sites because I do not run them. However I think I do have some valuable experience to relate here.

1. It does not happen on the initial load of the site. Once it starts happening, I can use the browser dev tools to clear all stored data related to the site in order to get it to load once.
2. On subsequent sessions, once the conflict arises, all JSON transferred appears to be via XHR and delivered by the service worker.

For both of these things to be true, it seems like JSONView must be inadvertently trying to convert data the data in the content page based on an is-json indication from the background worker that is being triggered by an XHR request.

**Comment by bhollis** [comment]
Yep that's definitely what's happening - but without a repro case I can't be sure if I've fixed it. So either I need access to a way to reproduce the issue, or someone who has that access needs to submit a fix.

**Comment by dvogel** [comment]
Are there any cases where we _do_ want an XHR request or a request other than the one for the content page to trigger a content re-formatting? Seems unlikely, but just curious if I need to keep this in mind while crafting a fix.

**Comment by bhollis** [comment]
Nope, it should only trigger for main frame load, not XHRs or subframes.

**Comment by bhollis** [comment]
I've published a version based on @dvogel's fix to all the stores. It usually takes a week or so for a new version to be reviewed and made available.

**Comment by sohang3112** [comment]
Having same issue with Sharepoint (sometimes not always). Good thing you fixed it @bhollis - thanks 👍. 

>It usually takes a week or so for a new version to be reviewed and made available.

But if I don't wanna wait a weak but install directly from here (yes i already know this can be dangerous ) then how in firefox? any guide?

**Comment by bhollis** [comment]
This should be fixed now. Please let me know if it's not, using the latest version.

**Comment by sohang3112** [comment]
@bhollis Hi, JSONView is showing greyed out for me on all sites (as you can see in the screenshot, other Firefox add-ons like UBlock are showing normally). Any idea how to fix this?

![JSONView greyed out extension](https://github.com/user-attachments/assets/4c6b89e8-8f99-4404-8420-2581096f55c6)

I'm using Firefox 135.0 on Fedora linux.

**Comment by hylkevds** [comment]
For me the problem is still there, though not as often. 
Using the FireFox debugger, it's triggering in the
```chrome.runtime.sendMessage("jsonview-is-json", (response) => {```
method, on a document that has content type set to text/html, and that contains only a `\n` (a linebreak).

**Comment by lordofthemoon** [comment]
I'm also still seeing it with the new version on Firefox. Unfortunately, our Sharepoint site is private, so I can't give a URL.

**Comment by bhollis** [comment]
Still waiting for one of:

1. Access to a SharePoint site that reproduces the issue.
2. A PR with a verified fix from someone else who has access.

**Comment by davetapley** [comment]
@bhollis try: https://jefuller-my.sharepoint.com/:f:/p/dave/Ekfwcyy9B91LtavFk5qHQXsBHrSeZ1D1oJL_hIR1WT7veg?e=f0c1Qe

```
Microsoft Edge for Business
Version 136.0.3240.64 (Official build) (x86_64)
```

<img width="758" alt="Image" src="https://github.com/user-attachments/assets/d5a63bb6-c3a6-4a67-a382-d47b0cd7f227" />

**Comment by bhollis** [comment]
Thanks. Once I had access, the fix was easy, and was largely what I expected. 

Apparently SharePoint will render pages from its service worker after the first load. The service worker downloads a JSON document and then processes it into HTML to return to the browser. However, they fail to change the content type header of the response, so they are effectively stating "This is JSON". For some reason (maybe even because of this same issue!) browsers are ignoring that and displaying the HTML anyway.

https://github.com/bhollis/jsonview/pull/226 is the fix, I'll get a new version out to the addon marketplaces soon and then the fixed version should be out in a few days.
